### PR TITLE
Explicitly mention the change of DQNAgent because of gradian clipping #0

### PR DESCRIPTION
**Pull request by AFanaei**

### CODE REVIEW

**Comment by Curt-Park** [comment]
Due to diff issue in ReviewNB, it's hard to find what you modified.
Could you mention you changed?
https://app.reviewnb.com/Curt-Park/rainbow-is-all-you-need/pull/55/

**Comment by AFanaei** [comment]
this merge request has only two changes in comments:

old:
> Here, DQNAgent is totally same as the one from *01.dqn.ipynb*.
new:
> There is only one diffrence between DQNAgent here and the one from *01.dqn.ipynb* and that is the usage of clip_grad_norm_ to prevent gradient exploding.

old:
> # we clip the gradients to have their norm less than or equal to 10.
new:
> # DuelingNet: we clip the gradients to have their norm less than or equal to 10.

BTW. you can see changes using [github.dev](https://github.dev/AFanaei/rainbow-is-all-you-need/tree/patch-2) it has no problem showing commit diff:

image

**Comment by Curt-Park** [comment]
I re-added the training progress plots and agent animations.
Thanks.

**Review by Curt-Park — APPROVED** [review]

**Comment by Curt-Park** [comment]
@all-contributors please add @AFanaei for doc

**Pull request merged**
