### PR TITLE
A Small Typo in 03.per

### PR DESCRIPTION
**Pull request by Wei-1**
`asmall` is probably `a small`?

### CODE REVIEW

**Comment by Curt-Park** [comment]
@all-contributors please add Wei-1 for maintenance

**Comment by Wei-1** [comment]
I think the `-` sign is bugging the bot?

**Comment by Curt-Park** [comment]
I will manually fix it

**Comment by Curt-Park** [comment]
Fixed at https://github.com/Curt-Park/rainbow-is-all-you-need/pull/32

**Pull request merged**
