### PR TITLE
Fix rendering issue

### PR DESCRIPTION
**Pull request by Curt-Park**
- issue from: https://www.facebook.com/groups/ReinforcementLearningKR/permalink/2397295550509671/

Changed playing a gif animation to saving and playing an mp4 file.

## Changes

```python
# Colab configurations
import sys
IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    !apt install python-opengl
    !apt install ffmpeg
    !apt install xvfb
    !pip install pyvirtualdisplay
    from pyvirtualdisplay import Display
    
    # Start virtual display
    dis = Display(visible=0, size=(400, 400))
    dis.start()
```

```python
# test method in Agent
def test(self) -> None:
        """Test the agent."""
        self.is_test = True
        
        state = self.env.reset()
        done = False
        score = 0
        
        while not done:
            self.env.render()
            action = self.select_action(state)
            next_state, reward, done = self.step(action)

            state = next_state
            score += reward
        
        print("score: ", score)
        self.env.close()
```

```python
# test
agent.env = gym.wrappers.Monitor(env, "videos", force=True)
agent.test()
```

```python
# render
import base64
import glob
import io
import os

from IPython.display import HTML, display


def ipython_show_video(path: str) -> None:
    """Show a video at `path` within IPython Notebook."""
    if not os.path.isfile(path):
        raise NameError("Cannot access: {}".format(path))

    video = io.open(path, "r+b").read()
    encoded = base64.b64encode(video)

    display(HTML(
        data="""
        <video alt="test" controls>
        <source src="data:video/mp4;base64,{0}" type="video/mp4"/>
        </video>
        """.format(encoded.decode("ascii"))
    ))

list_of_files = glob.glob("videos/*.mp4")
latest_file = max(list_of_files, key=os.path.getctime)
print(latest_file)
ipython_show_video(latest_file)
```

### CODE REVIEW

**Comment by Curt-Park** [comment]
@MrSyee I will take a close look at this change again tomorrow. Just see which parts are changed.

**Comment by Curt-Park** [comment]
It tends to show lower performance than before. I will tune the parameters again if needed.

**Comment by MrSyee** [comment]
It's a great job! I've checked this modification and test video rendering. I think `print(latest_file)` in the render block should be moved:
```
# render
import base64
import glob
import io
import os

from IPython.display import HTML, display


def ipython_show_video(path: str) -> None:
    """Show a video at `path` within IPython Notebook."""
    print(latest_file)  # should remove
    
    if not os.path.isfile(path):
        raise NameError("Cannot access: {}".format(path))

    video = io.open(path, "r+b").read()
    encoded = base64.b64encode(video)

    display(HTML(
        data="""
        <video alt="test" controls>
        <source src="data:video/mp4;base64,{0}" type="video/mp4"/>
        </video>
        """.format(encoded.decode("ascii"))
    ))

list_of_files = glob.glob("videos/*.mp4")
latest_file = max(list_of_files, key=os.path.getctime)
print(latest_file)  # should add
ipython_show_video(latest_file)
```

I'll update `pg-is-all-you-need` soon. Thank you.

**Comment by Curt-Park** [comment]
@MrSyee Thanks for your review. I fixed it.

**Pull request merged**
